# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [2]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [3]:
import numpy as np

**2. Print the numpy version and the configuration**

In [21]:
print("Version: ", np.__version__)
print("Configuration:")
np.show_config()

Version:  1.19.2
Configuration:
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/evano/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/evano/anaconda3/envs/enel645\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/evano/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/evano/anaconda3/envs/enel645\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/evano/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/evano/anaconda3/envs/enel645\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/evano/anaconda3/envs/enel645\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', No

**3. Create a 1D array of zeros of size 10 of type float32**

In [24]:
arr = np.zeros(10).astype('float32')
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

**4. Print the memory size of the array below**

In [10]:
Z = np.zeros((32,12))
# Include your solution below
print("Memory size of numpy array in bytes:",
      Z.size * Z.itemsize)

Memory size of numpy array in bytes: 3072


**5. Create a 1D array with values ranging from 10 to 58**

In [17]:
arr = np.arange(10,59)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [18]:
a = np.arange(10)
# Include your solution below
a_reversed = a[::-1]
print(a_reversed)

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [20]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [21]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [26]:
Z = np.random.random((10,11))
# Include your solution below
print(Z)

[[0.33658232 0.21573488 0.55602953 0.8318638  0.59049435 0.61599485
  0.42259749 0.50988772 0.66404432 0.5502104  0.52979443]
 [0.46014659 0.21496339 0.61874483 0.66229174 0.6144897  0.30387714
  0.66772715 0.36428397 0.64724382 0.56587565 0.40474113]
 [0.75541243 0.20085137 0.27578591 0.78460284 0.41302145 0.51023535
  0.3935228  0.35618118 0.0768668  0.60155785 0.0768577 ]
 [0.13961857 0.07636586 0.47330379 0.77918937 0.57406901 0.16903619
  0.27519456 0.59249349 0.22827727 0.05002648 0.90096557]
 [0.3800774  0.77256226 0.23360118 0.75751468 0.43940921 0.92638917
  0.23874588 0.27154957 0.97507307 0.6503613  0.38967867]
 [0.81894386 0.85335332 0.66480185 0.62577927 0.1053496  0.54115025
  0.21583517 0.16323451 0.98558608 0.30143355 0.39766521]
 [0.77162283 0.51821987 0.95224686 0.43401272 0.08280003 0.47917174
  0.54332861 0.83973474 0.01177111 0.2179449  0.10070865]
 [0.64915497 0.12953868 0.78997442 0.62726618 0.9841566  0.19829534
  0.00354378 0.22257276 0.85259547 0.89530375 0.82

In [28]:
print(Z.max(axis=0))


[0.86210498 0.85335332 0.95224686 0.8318638  0.9841566  0.92638917
 0.82869295 0.98254455 0.98558608 0.89530375 0.90096557]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [39]:
x = np.ones((7,7))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [40]:
Z = np.ones((5,5))
# Include your solution below
Z = np.pad(Z, 1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [36]:
Z = np.random.uniform(0,10,10)
# Include your solution below
Z_int = Z.astype('int')
print(Z_int)

[0 9 5 9 5 6 0 3 8 5]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [46]:
x = np.array([0,1,2,3,4])
# Broadcast
# y = np.ones(5).reshape(5,1)
# print(x*y)

# Tile
x = np.tile(x,(5,1))
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [51]:
#Linspace creates a vector of size 11 that includes 0. [1::] removes the zero value from the vector.
x = np.linspace(0,1,11, endpoint=False)[1::]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [52]:
x = np.random.rand(10)
x_sorted = np.sort(x)
print(x_sorted)

[0.06246644 0.14468559 0.42851676 0.65226776 0.71734878 0.72965331
 0.84139736 0.8802317  0.96564456 0.97724106]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [62]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
# print("R:\n" + str(R) + "\nT:\n" + str(T))
coordinates = tuple(zip(R,T))
print("(R, T):")
print(coordinates)

(R, T):
((0.4163375577226869, 0.2806044864420662), (0.07098137116215161, 0.4674365476503871), (1.0850726637473909, 0.4881540817450724), (0.6864680495293233, 0.21935742764929567), (0.981263193746768, 1.0079956848431855), (1.0123568607157123, 1.186193213249977), (0.47367488507975825, 0.20178349034148368), (0.5417918789642271, 0.40145488161197745), (0.6843407932122182, 0.5389223205695528), (0.5253584585875845, 1.4549514501346055))


**17. Create random vector of size 10 and replace the maximum value by 0**

In [64]:
X = np.random.rand(10)
print("Before:")
print(X)
X[X.argmax()] = 0
print("After:")
print(X)

Before:
[0.73508186 0.83264905 0.54699262 0.93591753 0.09107129 0.72986443
 0.45387567 0.47482861 0.3079175  0.97148107]
After:
[0.73508186 0.83264905 0.54699262 0.93591753 0.09107129 0.72986443
 0.45387567 0.47482861 0.3079175  0.        ]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [23]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
print("Array being inspected:")
print(Z)
idx = (np.abs(Z - z)).argmin()
print("Closest number in array to 0.5: " + str(Z[idx])) 


Array being inspected:
[0.94927367 0.3686108  0.94740399 0.94516627 0.99204573 0.66400276
 0.4900378  0.07016214 0.54203893 0.43155855]
Closest number in array to 0.5: 0.4900378027955028


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [67]:
Z = np.arange(1,6)[::-1]
print(Z)
# Include your solution below
nz = 3
Z2 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z2[::nz+1] = Z
print(Z2)

[5 4 3 2 1]
[5. 0. 0. 0. 4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [93]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
# Depending on how you interpret the question this can be solved by either reshaping A to (3,5,5) or reshaping B to (5,5,1).
# Reshaping A gives a result that is (5,5,3) while reshaping B gives a result that is (3,5,5).

B = B.reshape(5,5,1)
# A = A.reshape(3,5,5)
print(A*B)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [47]:
W = np.arange(30).reshape(6,5)
print(W)
# Include your solution below
print("Rearranged 1st and 2nd row:")
W[[0, 1]] = W[[1, 0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Rearranged 1st and 2nd row:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="Figures/bbox.png" width="150" /> 
<img src="Figures/bin_image.png" width="150" /> 

In [109]:
def bbox(img):
    #include your solution below
    white_pix = np.argwhere(img)
    (r1,c1) = white_pix.min(axis = 0)
    (r2,c2) = white_pix.max(axis = 0)
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [157]:
def moving_average_clean(x,N = 3):
    #define your function here
    #This only works if the size of x is divisible by N
    size = x.size
    x = x.reshape(x.size//N, N)
    average = x.mean(axis = 1)
    return average

def moving_average_robust(x,N = 3):
    # This handles any size x and N > 0 but requires the use of an explicit loop
    size = x.size
    split = np.array_split(x, np.ceil(size/N))
    means = np.zeros(int(np.ceil(size/N)))
    for (i, window) in enumerate(split):
        means[i] = window.mean()
    return means

a = np.arange(30)
N = 3
print(moving_average_clean(a,N))
# print(moving_average_robust(a,N))

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [164]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include your solution here
A = np.repeat(np.arange(C.size),C)
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [170]:
Z = np.random.randint(0,10,50)
print(Z)
# Include your solution below
mode = np.bincount(Z).argmax()
print(mode)

[5 9 7 1 1 3 5 2 3 4 5 3 8 7 5 4 3 4 4 7 6 9 9 4 0 4 7 2 8 8 2 8 7 0 3 5 7
 5 1 5 4 9 6 5 7 1 5 4 2 5]
5


**26. Write a function to return the n largest values of an array** 

In [278]:
Z = np.arange(1000000)
np.random.shuffle(Z)
n = 5

In [308]:
def nlargest_sort(a,n = 5):
    # Include your solution here
    sorted = np.sort(a)
    largest = sorted[-1:-n-1:-1]
    return largest

In [296]:
def nlargest_part(a, n = 5):
    # Include your solution here
    temp = np.partition(-a,n)
    return np.sort(-temp[:n])[::-1]

In [282]:
def nlargest_iter(a,n = 5):
    # Include your solution here
    a = np.copy(a)
    largest = np.zeros(n)
    for i in range(n):
        ind = np.argmax(a)
        largest[i] = a[ind]
        a[ind] = 0
    return largest

In [283]:
%%timeit
nlargest_sort(Z,n)

54.4 ms ± 491 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [295]:
%%timeit
nlargest_part(Z,n)

8.8 ms ± 441 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [285]:
%%timeit
nlargest_iter(Z,n)

3.89 ms ± 126 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In this case the explicit iterative solution has **significantly** better performance than the sorting solution and mildly better performance than using np.partition. But as shown below, all three methods work.

In [286]:
print(nlargest_iter(Z,n))

[999999. 999998. 999997. 999996. 999995.]


In [ ]:
print(nlargest_part(Z,n))

[999999 999998 999997 999996 999995]


In [309]:
print(nlargest_sort(Z,n))

[999999 999998 999997 999996 999995]
