# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [2]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [3]:
import numpy as np

**2. Print the numpy version and the configuration**

In [3]:
print(np.__version__)
print(np.show_config())

1.21.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/brendanmahler/opt/anaconda3/envs/enel645/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/brendanmahler/opt/anaconda3/envs/enel645/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/brendanmahler/opt/anaconda3/envs/enel645/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/brendanmahler/opt/anaconda3/envs/enel645/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/brendanmahler/opt/anaconda3/envs/enel645/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/brendanmahler/opt/anaconda3/envs/enel645/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/brendanmahler/opt/anaconda3/envs/enel645/lib']
    define_macros = [('SCIPY_MKL_H', None)

**3. Create a 1D array of zeros of size 10 of type float32**

In [9]:
arr = np.zeros(10).astype('float32')

**4. Print the memory size of the array below**

In [10]:
Z = np.zeros((32,12))
# Include your solution below
print("Memory size of numpy array in bytes:",
      Z.size * Z.itemsize)

Memory size of numpy array in bytes: 3072


**5. Create a 1D array with values ranging from 10 to 58**

In [17]:
arr = np.arange(10,59)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [18]:
a = np.arange(10)
# Include your solution below
a_reversed = a[::-1]
print(a_reversed)

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [20]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [21]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [27]:
Z = np.random.random((10,11))
# Include your solution below
print(Z)

[[0.12262722 0.0942089  0.65179432 0.02898614 0.17930944 0.81366505
  0.12371039 0.44795636 0.74116671 0.8308242  0.79809956]
 [0.4657579  0.68969487 0.50868532 0.83360466 0.76474197 0.24723552
  0.94361436 0.73724483 0.57575236 0.541649   0.84878357]
 [0.22634973 0.77463419 0.28025994 0.38889128 0.46291771 0.59399222
  0.1426368  0.15536889 0.06630826 0.12175317 0.69280706]
 [0.8008414  0.22084268 0.15516598 0.51007502 0.26105186 0.49905975
  0.86754924 0.6565374  0.21213192 0.61073676 0.28684623]
 [0.34583843 0.28150978 0.43952941 0.25640413 0.85755685 0.307569
  0.23597498 0.48413186 0.94325755 0.01988571 0.02675831]
 [0.46842806 0.98112727 0.55029434 0.53873716 0.54351888 0.86243554
  0.44202106 0.1118274  0.79545414 0.06694293 0.68432492]
 [0.74812143 0.76945355 0.52739492 0.93726969 0.61428614 0.43034813
  0.31078273 0.00744925 0.58024736 0.91736814 0.39021769]
 [0.33624838 0.64740327 0.77124948 0.79173065 0.11732721 0.82510597
  0.30421686 0.07724339 0.6686664  0.94614175 0.6463

In [24]:
print(Z.max(axis=0))


[0.83639785 0.91896066 0.97417507 0.97891885 0.9202992  0.96120457
 0.98692052 0.95161041 0.97647271 0.96740752 0.9367386 ]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [39]:
x = np.ones((7,7))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [40]:
Z = np.ones((5,5))
# Include your solution below
Z = np.pad(Z, 1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [43]:
Z = np.random.uniform(0,10,10)
# Include your solution below
Z_int = Z.astype('int')
print(Z_int)

[8 9 3 9 2 6 9 7 6 8]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [48]:
x = np.array([0,1,2,3,4])
x = np.tile(x,(5,1))
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [59]:
x = np.linspace(0,1,11, endpoint=False)[1::]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [64]:
x = np.random.rand(10)
x_sorted = np.sort(x)
print(x_sorted)

[0.03860492 0.12348382 0.15740345 0.62866715 0.64504393 0.73841819
 0.84238496 0.87083128 0.89127711 0.90506661]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [5]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R,T)

[0.68004747 0.7924818  0.23460053 1.01207406 0.76543887 0.61148339
 0.76814628 0.51230351 0.85629878 0.42148013] [0.06495407 0.19506399 0.922117   1.20609892 0.75843082 0.63844768
 1.19689172 1.49590354 0.67425578 1.23910566]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [14]:
X = np.random.rand(10)
X[X.argmax()] = 0
print(X)

[0.25707582 0.55796723 0.21669545 0.47093352 0.60186453 0.
 0.78796195 0.0291731  0.32032448 0.00413745]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [23]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
print("Array being inspected:")
print(Z)
idx = (np.abs(Z - z)).argmin()
print("Closest number in array to 0.5: " + str(Z[idx])) 


Array being inspected:
[0.94927367 0.3686108  0.94740399 0.94516627 0.99204573 0.66400276
 0.4900378  0.07016214 0.54203893 0.43155855]
Closest number in array to 0.5: 0.4900378027955028


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [39]:
Z = np.arange(5)[::-1]
# Include your solution below
nz = 3
Z2 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z2[::nz+1] = Z
print(Z2)

[4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [50]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
#Is this right????
C = np.dot(B,A)
print(C)

[[[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]

 [[10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]
  [10. 10. 10.]]]


**21. Swap the first and second rows of the 2D array below**

In [47]:
W = np.arange(30).reshape(6,5)
print(W)
# Include your solution below
print("Rearranged 1st and 2nd row:")
W[[0, 1]] = W[[1, 0]]
print(W)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Rearranged 1st and 2nd row:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="../Figures/bbox.png" width="150" /> 

In [ ]:
def bbox(img):
    #include your solution below
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('../Figures/bin_image.png').convert('L')) > 0
print(bbox(img))

**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [ ]:
def moving_average(x,N = 3):
    #define your function here
    return

a = np.arange(30)
N = 3
print(moving_average(a,N))

**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here

**25. Find the most frequent value in the array below?**

In [ ]:
Z = np.random.randint(0,10,50)
# Include your solution below

**26. Write a function to return the n largest values of an array** 

In [ ]:
def nlargest(a,n = 5):
    # Include your solution here
    
    return

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    